# Generated by Django 3.0.6 on 2020-06-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('author', models.CharField(max_length=500)),
                ('postId', models.IntegerField(primary_key=True, serialize=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('datePosted', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(default=None, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('author', models.CharField(max_length=500)),
                ('commentId', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('commentTime', models.DateTimeField(verbose_name='date commented')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspost.NewsPost')),
            ],
        ),
    ]
