# Generated by Django 3.0.6 on 2020-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0002_auto_20200601_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='url',
            field=models.CharField(default=None, max_length=300, unique=True),
        ),
    ]
