# Generated by Django 3.0.6 on 2020-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0004_auto_20200601_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
