# Generated by Django 3.0.6 on 2020-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0005_auto_20200602_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='commentCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
