# Generated by Django 3.0.6 on 2020-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0006_newspost_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
